version: '2'

services:
    goswift-mongo:
        image: mongo
        volumes:
            - goswiftmongo:/data/db

    goswift-frontend:
        image: osallou/goswift-frontend
        ports:
            - "8080:80"
        environment:
            - REACT_APP_GOSWIFT_BACKEND_URL=${REACT_APP_GOSWIFT_BACKEND_URL}
            - REACT_APP_GOSWIFT_SWITF_URL=${REACT_APP_GOSWIFT_SWITF_URL}
        build:
            context: .
            dockerfile: Dockerfile-frontend

    goswift-backend:
        image: osallou/goswift-backend
        build:
            context: .
            dockerfile: Dockerfile-backend
        environment:
            - GOSWIFT_SALT_SECRET=${GOSWIFT_SALT_SECRET}
            - GOSWIFT_SWIFT_KEYSTONE_URL=${GOSWIFT_SWIFT_KEYSTONE_URL}
            - GOSWIFT_SWIFT_SWIFT_URL=${GOSWIFT_SWIFT_SWIFT_URL}
            - GOSWIFT_SWIFT_ADMIN_OS_USER_ID=${GOSWIFT_SWIFT_ADMIN_OS_USER_ID}
            - GOSWIFT_SWIFT_ADMIN_OS_USER_PASSWORD=${GOSWIFT_SWIFT_ADMIN_OS_USER_PASSWORD}
            - GOSWIFT_SWIFT_ADMIN_OS_USER_PROJECT=${GOSWIFT_SWIFT_ADMIN_OS_USER_PROJECT}
            - GOSWIFT_SWIFT_ADMIN_OS_USER_DOMAIN=${GOSWIFT_SWIFT_ADMIN_OS_USER_DOMAIN}
            - GOSWIFT_SWIFT_DEFAULTS_DOMAIN=${GOSWIFT_SWIFT_DEFAULTS_DOMAIN}
            - GOSWIFT_SWIFT_QUOTAS=${GOSWIFT_SWIFT_QUOTAS}
            - GOSWIFT_ELASTIC_HOST=goswift-elastic
            - GOSWIFT_MONGO_URL=mongodb://goswift-mongo:27017
            - GOSWIFT_ADMIN_LIST=bioinfo
            - GOSWIFT_SMTP_HOST=${GOSWIFT_SMTP_HOST}
            - GOSWIFT_SMTP_PORT=25

    goswift-elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
        environment:
            - discovery.type=single-node
        ulimits:
          memlock:
             soft: -1
             hard: -1
        volumes:
          - esdata1:/usr/share/elastcisearch/data

volumes:
  esdata1:
    driver: local
  goswiftmongo:
    driver: local
